version: '3.3'

services:

  redis_tls_shopview:
    container_name: redis_tls_shopview
    build:
      context: ./redis-sharding/redis-tls-container/
    ports:
      - "6375:6375"
    volumes:
      - ./redis-sharding/redis-tls-container/certs:/etc/certs
