// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: create-delete-message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiKey              string            `protobuf:"bytes,19,opt,name=ApiKey,proto3" json:"ApiKey,omitempty"`
	Token               string            `protobuf:"bytes,48,opt,name=Token,proto3" json:"Token,omitempty"`
	ShopName            string            `protobuf:"bytes,20,opt,name=ShopName,proto3" json:"ShopName,omitempty"`
	Images              []string          `protobuf:"bytes,22,rep,name=Images,proto3" json:"Images,omitempty"`
	PrimaryImage        string            `protobuf:"bytes,23,opt,name=PrimaryImage,proto3" json:"PrimaryImage,omitempty"`
	Address             *Address          `protobuf:"bytes,24,opt,name=Address,proto3" json:"Address,omitempty"`
	Location            *Location         `protobuf:"bytes,25,opt,name=Location,proto3" json:"Location,omitempty"`
	Category            []Category        `protobuf:"varint,26,rep,packed,name=Category,proto3,enum=Category" json:"Category,omitempty"`
	BusinessInformation string            `protobuf:"bytes,27,opt,name=BusinessInformation,proto3" json:"BusinessInformation,omitempty"`
	OperationalHours    *OperationalHours `protobuf:"bytes,28,opt,name=OperationalHours,proto3" json:"OperationalHours,omitempty"`
}

func (x *CreateShopRequest) Reset() {
	*x = CreateShopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_delete_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShopRequest) ProtoMessage() {}

func (x *CreateShopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_create_delete_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShopRequest.ProtoReflect.Descriptor instead.
func (*CreateShopRequest) Descriptor() ([]byte, []int) {
	return file_create_delete_message_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShopRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *CreateShopRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateShopRequest) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *CreateShopRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CreateShopRequest) GetPrimaryImage() string {
	if x != nil {
		return x.PrimaryImage
	}
	return ""
}

func (x *CreateShopRequest) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *CreateShopRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *CreateShopRequest) GetCategory() []Category {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *CreateShopRequest) GetBusinessInformation() string {
	if x != nil {
		return x.BusinessInformation
	}
	return ""
}

func (x *CreateShopRequest) GetOperationalHours() *OperationalHours {
	if x != nil {
		return x.OperationalHours
	}
	return nil
}

type CreateShopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,28,opt,name=Ok,proto3" json:"Ok,omitempty"`
}

func (x *CreateShopResponse) Reset() {
	*x = CreateShopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_delete_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShopResponse) ProtoMessage() {}

func (x *CreateShopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_create_delete_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShopResponse.ProtoReflect.Descriptor instead.
func (*CreateShopResponse) Descriptor() ([]byte, []int) {
	return file_create_delete_message_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShopResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DeleteShopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  string `protobuf:"bytes,29,opt,name=Token,proto3" json:"Token,omitempty"`
	ApiKey string `protobuf:"bytes,30,opt,name=ApiKey,proto3" json:"ApiKey,omitempty"` // Later Add OTP Conformation For Deletion Of Shop
}

func (x *DeleteShopRequest) Reset() {
	*x = DeleteShopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_delete_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteShopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShopRequest) ProtoMessage() {}

func (x *DeleteShopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_create_delete_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShopRequest.ProtoReflect.Descriptor instead.
func (*DeleteShopRequest) Descriptor() ([]byte, []int) {
	return file_create_delete_message_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteShopRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DeleteShopRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type DeleteShopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,31,opt,name=Ok,proto3" json:"Ok,omitempty"`
}

func (x *DeleteShopResponse) Reset() {
	*x = DeleteShopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_delete_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteShopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShopResponse) ProtoMessage() {}

func (x *DeleteShopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_create_delete_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShopResponse.ProtoReflect.Descriptor instead.
func (*DeleteShopResponse) Descriptor() ([]byte, []int) {
	return file_create_delete_message_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteShopResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type AddProductRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token            string     `protobuf:"bytes,32,opt,name=Token,proto3" json:"Token,omitempty"`
	ApiKey           string     `protobuf:"bytes,33,opt,name=ApiKey,proto3" json:"ApiKey,omitempty"`
	Title            string     `protobuf:"bytes,34,opt,name=Title,proto3" json:"Title,omitempty"`
	ShortDescription string     `protobuf:"bytes,35,opt,name=ShortDescription,proto3" json:"ShortDescription,omitempty"`
	Description      string     `protobuf:"bytes,36,opt,name=Description,proto3" json:"Description,omitempty"`
	ShippingInfo     string     `protobuf:"bytes,37,opt,name=ShippingInfo,proto3" json:"ShippingInfo,omitempty"`
	Stock            uint32     `protobuf:"varint,38,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Price            float32    `protobuf:"fixed32,39,opt,name=Price,proto3" json:"Price,omitempty"`
	Offer            uint32     `protobuf:"varint,40,opt,name=Offer,proto3" json:"Offer,omitempty"`
	Images           []string   `protobuf:"bytes,41,rep,name=Images,proto3" json:"Images,omitempty"`
	Category         []Category `protobuf:"varint,42,rep,packed,name=Category,proto3,enum=Category" json:"Category,omitempty"`
}

func (x *AddProductRequest) Reset() {
	*x = AddProductRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_delete_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductRequest) ProtoMessage() {}

func (x *AddProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_create_delete_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductRequest.ProtoReflect.Descriptor instead.
func (*AddProductRequest) Descriptor() ([]byte, []int) {
	return file_create_delete_message_proto_rawDescGZIP(), []int{4}
}

func (x *AddProductRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AddProductRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AddProductRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddProductRequest) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *AddProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddProductRequest) GetShippingInfo() string {
	if x != nil {
		return x.ShippingInfo
	}
	return ""
}

func (x *AddProductRequest) GetStock() uint32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *AddProductRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddProductRequest) GetOffer() uint32 {
	if x != nil {
		return x.Offer
	}
	return 0
}

func (x *AddProductRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *AddProductRequest) GetCategory() []Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type AddProductResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,43,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *AddProductResponse) Reset() {
	*x = AddProductResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_delete_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductResponse) ProtoMessage() {}

func (x *AddProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_create_delete_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductResponse.ProtoReflect.Descriptor instead.
func (*AddProductResponse) Descriptor() ([]byte, []int) {
	return file_create_delete_message_proto_rawDescGZIP(), []int{5}
}

func (x *AddProductResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DelProductRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token     string `protobuf:"bytes,44,opt,name=Token,proto3" json:"Token,omitempty"`
	ApiKey    string `protobuf:"bytes,45,opt,name=ApiKey,proto3" json:"ApiKey,omitempty"`
	ProductId string `protobuf:"bytes,46,opt,name=ProductId,proto3" json:"ProductId,omitempty"`
}

func (x *DelProductRequest) Reset() {
	*x = DelProductRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_delete_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelProductRequest) ProtoMessage() {}

func (x *DelProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_create_delete_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelProductRequest.ProtoReflect.Descriptor instead.
func (*DelProductRequest) Descriptor() ([]byte, []int) {
	return file_create_delete_message_proto_rawDescGZIP(), []int{6}
}

func (x *DelProductRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DelProductRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *DelProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type DelProductResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,47,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *DelProductResponse) Reset() {
	*x = DelProductResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_delete_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelProductResponse) ProtoMessage() {}

func (x *DelProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_create_delete_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelProductResponse.ProtoReflect.Descriptor instead.
func (*DelProductResponse) Descriptor() ([]byte, []int) {
	return file_create_delete_message_proto_rawDescGZIP(), []int{7}
}

func (x *DelProductResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_create_delete_message_proto protoreflect.FileDescriptor

var file_create_delete_message_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2d, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x2d,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x73,
	0x68, 0x6f, 0x70, 0x2d, 0x76, 0x69, 0x65, 0x77, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2d,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfc, 0x02,
	0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x18, 0x13, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x30, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x14, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x68, 0x6f, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x16, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x17, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x50, 0x72, 0x69,
	0x6d, 0x61, 0x72, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x07, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x18, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x25, 0x0a,
	0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x19, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x18, 0x1a, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x52, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x30, 0x0a, 0x13, 0x42,
	0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x1b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65,
	0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3d, 0x0a,
	0x10, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x48, 0x6f, 0x75, 0x72,
	0x73, 0x18, 0x1c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x52, 0x10, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x22, 0x24, 0x0a, 0x12,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x1c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02,
	0x4f, 0x6b, 0x22, 0x41, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x1d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x41, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41,
	0x70, 0x69, 0x4b, 0x65, 0x79, 0x22, 0x24, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x68, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x4f,
	0x6b, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x4f, 0x6b, 0x22, 0xca, 0x02, 0x0a, 0x11,
	0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x20, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x70, 0x69, 0x4b, 0x65,
	0x79, 0x18, 0x21, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x22, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x23, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x10, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x24, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x25, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x53, 0x68, 0x69, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x18, 0x26, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x14, 0x0a,
	0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x27, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x18, 0x28, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x73, 0x18, 0x29, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x73, 0x12, 0x25, 0x0a, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x2a, 0x20,
	0x03, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x08,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x24, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x2b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x5f,
	0x0a, 0x11, 0x44, 0x65, 0x6c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x2c, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x70, 0x69,
	0x4b, 0x65, 0x79, 0x18, 0x2d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x70, 0x69, 0x4b, 0x65,
	0x79, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x2e,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x22,
	0x24, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x2f, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x02, 0x6f, 0x6b, 0x42, 0x30, 0x0a, 0x26, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x61, 0x70,
	0x61, 0x6e, 0x61, 0x76, 0x79, 0x61, 0x70, 0x61, 0x72, 0x2e, 0x61, 0x61, 0x70, 0x61, 0x6e, 0x61,
	0x76, 0x79, 0x61, 0x70, 0x61, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x50,
	0x01, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_create_delete_message_proto_rawDescOnce sync.Once
	file_create_delete_message_proto_rawDescData = file_create_delete_message_proto_rawDesc
)

func file_create_delete_message_proto_rawDescGZIP() []byte {
	file_create_delete_message_proto_rawDescOnce.Do(func() {
		file_create_delete_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_create_delete_message_proto_rawDescData)
	})
	return file_create_delete_message_proto_rawDescData
}

var file_create_delete_message_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_create_delete_message_proto_goTypes = []interface{}{
	(*CreateShopRequest)(nil),  // 0: CreateShopRequest
	(*CreateShopResponse)(nil), // 1: CreateShopResponse
	(*DeleteShopRequest)(nil),  // 2: DeleteShopRequest
	(*DeleteShopResponse)(nil), // 3: DeleteShopResponse
	(*AddProductRequest)(nil),  // 4: AddProductRequest
	(*AddProductResponse)(nil), // 5: AddProductResponse
	(*DelProductRequest)(nil),  // 6: DelProductRequest
	(*DelProductResponse)(nil), // 7: DelProductResponse
	(*Address)(nil),            // 8: Address
	(*Location)(nil),           // 9: Location
	(Category)(0),              // 10: Category
	(*OperationalHours)(nil),   // 11: OperationalHours
}
var file_create_delete_message_proto_depIdxs = []int32{
	8,  // 0: CreateShopRequest.Address:type_name -> Address
	9,  // 1: CreateShopRequest.Location:type_name -> Location
	10, // 2: CreateShopRequest.Category:type_name -> Category
	11, // 3: CreateShopRequest.OperationalHours:type_name -> OperationalHours
	10, // 4: AddProductRequest.Category:type_name -> Category
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_create_delete_message_proto_init() }
func file_create_delete_message_proto_init() {
	if File_create_delete_message_proto != nil {
		return
	}
	file_shop_view_common_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_create_delete_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateShopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_create_delete_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateShopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_create_delete_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteShopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_create_delete_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteShopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_create_delete_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddProductRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_create_delete_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddProductResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_create_delete_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelProductRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_create_delete_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelProductResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_create_delete_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_create_delete_message_proto_goTypes,
		DependencyIndexes: file_create_delete_message_proto_depIdxs,
		MessageInfos:      file_create_delete_message_proto_msgTypes,
	}.Build()
	File_create_delete_message_proto = out.File
	file_create_delete_message_proto_rawDesc = nil
	file_create_delete_message_proto_goTypes = nil
	file_create_delete_message_proto_depIdxs = nil
}
